### ISSUE TITLE
Drupal can't clear cache

### ISSUE THREAD

**Issue by kobeaerts** [frizinak/drupony#1]
https://i.imgur.com/xvjKJoI.png

**Comment by frizinak** [comment]
soz freddi, I wholeheartedly refuse to fix your drupal+vagrant setup.

**Comment by kobeaerts** [comment]
Its ok man, Drupal just sucks!

On Mon, 28 Nov 2016 at 09:17 Kobe Lipkens

<
mailto:Kobe Lipkens <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

soz freddi, I wholeheartedly refuse to fix your drupal+vagrant setup.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/frizinak/drupony/issues/1#issuecomment-263208576
, or
